// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deletefeedfollow.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteFeedFollow = `-- name: DeleteFeedFollow :exec
DELETE FROM feed_follow WHERE ( user_id = $1 AND feed_id = $2 )
`

type DeleteFeedFollowParams struct {
	UserID uuid.NullUUID
	FeedID sql.NullInt32
}

func (q *Queries) DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollow, arg.UserID, arg.FeedID)
	return err
}
