// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getfeedfollowsforuser.sql

package database

import (
	"context"
	"database/sql"
)

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
SELECT feed.name AS feed_name, users.name AS user_name
FROM feed_follow
INNER JOIN users
ON feed_follow.user_id = users.id 
INNER JOIN feed
ON feed_follow.feed_id = feed.id
WHERE users.name = $1
`

type GetFeedFollowsForUserRow struct {
	FeedName sql.NullString
	UserName string
}

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, name string) ([]GetFeedFollowsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsForUserRow
	for rows.Next() {
		var i GetFeedFollowsForUserRow
		if err := rows.Scan(&i.FeedName, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
