// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: markfeedfetched.sql

package database

import (
	"context"
	"database/sql"
)

const markFeedFetched = `-- name: MarkFeedFetched :exec
UPDATE feed
SET updated_at=$1, last_fetched_at=$2
WHERE id=$3
`

type MarkFeedFetchedParams struct {
	UpdatedAt     sql.NullTime
	LastFetchedAt sql.NullTime
	ID            int32
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markFeedFetched, arg.UpdatedAt, arg.LastFetchedAt, arg.ID)
	return err
}
