// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resetfeed.sql

package database

import (
	"context"
)

const resetFeed = `-- name: ResetFeed :exec
DELETE FROM feed
`

func (q *Queries) ResetFeed(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetFeed)
	return err
}
